version: 2.1
orbs:
  core: ren/core@0.0.1
executors:
  go_exec:
    docker:
      - image: circleci/golang:1.12
jobs:
  build:
    executor: go_exec
    steps:
      - checkout
      - restore_cache: # Restore saved cache if no changes are detected since last run
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install tools
          command: |
            go get -u golang.org/x/lint/golint
            go get -u github.com/onsi/ginkgo/ginkgo
            go get -u github.com/loongy/covermerge
            go get -u github.com/mattn/goveralls
      - run:
          name: Run tests
          command: |
            # make sure all the tests pass
            go test -v ./...
            # all the tests passed so update coverage
            CI=true /go/bin/ginkgo -v --race --cover --coverprofile coverprofile.out ./...
            /go/bin/covermerge \
            validator/coverprofile.out \
            coverprofile.out \
            dispatcher/coverprofile.out \
            server/ratelimiter/coverprofile.out \
            server/coverprofile.out \
            updater/coverprofile.out \
            client/coverprofile.out \
            cacher/coverprofile.out \
            store/coverprofile.out > covermerge.out
            goveralls -coverprofile=covermerge.out -service=circleci
      - run:
          name: Run linter
          command: golint ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 16 * * *" # Every day at 16:00 UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - core/merge_nightly:
          executor: go_exec
  weekly:
    triggers:
      - schedule:
          cron: "0 23 * * 0" # Every Sunday at 23:00 UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - core/merge_beta:
          executor: go_exec
