version: 2.1
orbs:
    core: ren/circleci-orbs@dev:first
jobs:
  build:
    docker:
      - image: circleci/golang:1.12      
    steps:
      - checkout
      - restore_cache: # Restore saved cache if no changes are detected since last run
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  nightly:
      triggers:
        - schedule:
            cron: "0 2 * * *" # Every night at 02:00
            filters:
              branches:
                only:
                  - master
      jobs:
        - core/merge:
            from: master
            into: nightly
  weekly:
      triggers:
        - schedule:
            cron: "0 9 * * 1" # Every Monday at 09:00
            filters:
              branches:
                only:
                  - master
      jobs:
        - core/merge:
            from: nightly
            into: beta