version: 2
jobs:
  build:
    working_directory: /go/src/github.com/republicprotocol/lightnode
    docker:
      - image: circleci/golang:1.12      
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -v ./...
      - run: go test -v ./...
