name: go
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://tok-kkk:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Caching modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-lightnode-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        run: |
          sudo apt install ocl-icd-opencl-dev
          git submodule add https://github.com/filecoin-project/filecoin-ffi.git .extern/filecoin-ffi
          cd .extern/filecoin-ffi
          git checkout a62d00da59d1b0fb35f3a4ae854efa9441af892d
          make
          cd ../..
          go mod edit -replace=github.com/filecoin-project/filecoin-ffi=./.extern/filecoin-ffi
      - name: Get dependencies
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          go get -u golang.org/x/lint/golint
          go get -u github.com/loongy/covermerge
          go get -u github.com/mattn/goveralls
          cd $GITHUB_WORKSPACE
          go vet ./...
          golint ./...
      - name: Run tests and report test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          cd $GITHUB_WORKSPACE
          CI=true ginkgo --v --race --cover --coverprofile coverprofile.out ./...
          covermerge                                  \
            cacher/coverprofile.out                   \
            confirmer/coverprofile.out                \
            db/coverprofile.out                       \
            dispatcher/coverprofile.out               \
            http/coverprofile.out                     \
            store/coverprofile.out                    \
            updater/coverprofile.out                  \
            watcher/coverprofile.out                  \
            resolver/coverprofile.out > covermerge.out
          goveralls -coverprofile=coverprofile.out -service=github
